server:
  port: ${SERVER_PORT:8080}

management:
  server:
    port: ${MANAGEMENT_PORT:9080}
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"
info:
  build:
    name: '@project.name@'
    description: '@project.description@'
    group: '@project.groupId@'
    artifact: '@project.artifactId@'
    version: '@project.version@'

coin-calculator:
  limit:
    minBuy: 25
    maxBuy: 5000
  priceExpireInSeconds: 10